sudo: false
dist: trusty

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.2
      env: WP_VERSION=latest

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - bash tests/bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - composer global require "phpunit/phpunit=^6"

script:
  - phpunit --no-coverage
